services:

  nextjs:
    image: ${ECR_IMAGE}
    container_name: nextjs-app
    restart: always

    environment:
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}

    ports:
      - "3000:3000"

    depends_on:
      mongodb:
        condition: service_healthy

    networks:
      - app-network


  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongodb_data:/data/db

    networks:
      - app-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval \"db.adminCommand('ping')\""
        ]
      interval: 10s
      timeout: 5s
      retries: 10


networks:
  app-network:
    driver: bridge


volumes:
  mongodb_data: